name: 'Upload Asset'
description: 'Upload Asset to a Release'
inputs:
  url:
    description: 'Release upload url'
    required: true
  name:
    description: 'Asset name'
    required: true
  path:
    description: 'Asset path'
    required: true
outputs:
  url:
    description: 'Asset download url'
runs:
  using: 'node12'
  main: 'index.js'
