name: 'Create a Release'
description: 'Create a release'
author: 'Gregor Anders <gregor.ander@gmail.com>'
inputs:
  tag:
    description: 'Tag name'
    required: true
  name:
    description: 'Release name'
    required: true
  body:
    description: 'Release description'
    required: false
  draft:
    description: '`true` for a draft. `false` to publish. Default: `false`'
    required: false
    default: false
  prerelease:
    description: '`true` for a prerelease. `false` for a full release. Default: `false`'
    required: false
    default: false
  target:
    description: 'Release target (branch name or commit id)'
    required: false
    default: 'master'
outputs:
  id:
    description: 'Release Id'
  url:
    description: 'Release Url'
  upload_url:
    description: 'Release Asset Upload Url'
runs:
  using: 'node12'
  main: 'index.js'
