# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Release CI

on:
  release:
    types:
      - edited

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2016]
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and github actions
      run: |
        npm install
        npm run actions
    - name: prebuild
      id: prebuild
      uses: ./.github/actions/build-info
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_BRANCH: ${{ github.ref }}
        GITHUB_COMMIT: ${{ github.sha }}
    - name: npm install, build, test and dist
      run: |
        npm install
        npm run build
        npm test
        npm run dist
      env:
        CI: true
        GITHUB_CONTEXT: ${{ toJson(github) }}
        GITHUB_BRANCH: ${{ github.ref }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_BASE_REF: ${{ github.base_ref }}
        GITHUB_COMMIT: ${{ github.sha }}
    - name: test coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/lcov.info
    - name: prepare release
      id: prepare
      uses: ./.github/actions/prepare-release
      with:
        path: ./dist/pkg
    - name: release
      id: release
      uses: ./.github/actions/create-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: v${{ steps.prebuild.outputs.version }}
        name: ${{ steps.prebuild.outputs.version }} Release
        body: ${{ steps.prebuild.outputs.version }}
        target: ${{ github.ref }}
        draft: true
        prerelease: false
    - name: upload
      id: upload
      uses: ./.github/actions/upload-asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        url: ${{ steps.release.outputs.upload_url }}
        name: ${{ steps.prepare.outputs.name }}
        path: ${{ steps.prepare.outputs.path }}
